# config/deploy.yml
service: ai-chatbot
image: ashleyrudland87/ai-chatbot
servers:
    - <%= ENV["VPS_IP"] %>
registry:
    username:
        - KAMAL_REGISTRY_USERNAME
    password:
        - KAMAL_REGISTRY_PASSWORD
port: 3000
volumes:
  - "ai-chatbot-data:/ai-chatbot-data/"
